plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "bin/*"
    - "config/boot.rb"
    - "config/environment.rb"
    - "config/initializers/*.rb"
    - "vendor/**/*"
    - "node_modules/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

Rails/FilePath:
  Enabled: false

Performance:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 150
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"
    - "test/**/*"

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 10
