FROM ruby:3.4.4-slim

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  libxml2-dev \
  libxslt1-dev \
  zlib1g-dev \
  libgmp-dev \
  ruby-dev \
  curl \
  nodejs \
  npm \
  libyaml-dev \
  libffi-dev \
  libssl-dev \
  pkg-config

WORKDIR /rails

ENV BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

RUN chmod +x bin/docker-entrypoint

EXPOSE 3000

CMD ["bin/docker-entrypoint", "rails", "server", "-b", "0.0.0.0"]