FROM ruby:3.1.1-slim

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  libxml2-dev \
  libxslt1-dev \
  zlib1g-dev \
  libgmp-dev \
  ruby-dev \
  curl \
  nodejs \
  npm

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

RUN chmod +x bin/docker-entrypoint

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]