FROM ruby:3.1.1-slim

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev libvips curl nodejs npm && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy app
COPY . .

# Create entrypoint script
RUN chmod +x bin/docker-entrypoint

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]